name: MsccGenerativeAI

on:
  push:
    tags:
      - 'v*'
    paths:
      - '**'
      - '.github/workflows/dotnetcore.yml'
      - '!**.md'
      - '!docs/**'
      - '!samples/**'
      - '!tests/**'
      - '!LICENSE'
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/dotnetcore.yml'
      - '!**.md'
      - '!docs/**'
      - '!samples/**'
      - '!tests/**'
      - '!LICENSE'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 3.0.0)'
        required: true
        default: '3.0.0'
        type: string

jobs:
  build_and_push_main:
    name: Build and Push Main Package to Codeberg
    strategy:
      matrix:
        os: [codeberg-small]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['10.x']
    runs-on: ${{ matrix.os }}

    steps:
      - name: enable windows longpaths
        run: |
          git config --global core.longpaths true

#      - name: Install Cosign
#        uses: sigstore/cosign-installer@v3.6.0
#      - name: Check Cosign install!
#        run: cosign version

      - name: 📥 Check-out latest sources
        uses: actions/checkout@v6

      - name: 🔧 Set up .NET
        uses: https://github.com/actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
#          source-url: https://nuget.pkg.github.com/mscraftsman/index.json
        env:
#          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      
      # NetFX testing on non-Windows requires mono
      - name: 🔧 Setup Mono
        if: runner.os == 'Linux'
        run: sudo apt-get install -y mono-devel

      - name: 🏗️ Build for .NET
        run: dotnet build ./src/Mscc.GenerativeAI/Mscc.GenerativeAI.csproj -c Release

      - name: 📦 Pack for .NET
        run: dotnet pack -c Release ./src/Mscc.GenerativeAI/Mscc.GenerativeAI.csproj -o output/ --no-build

      - name: Set NuGet source
        run: mv ./nuget.codeberg ./nuget.config

#      - name: Setup access to Codeberg Package Registry
#        run: dotnet nuget add source --username ${{ vars.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name ghmain "https://nuget.pkg.github.com/mscraftsman/index.json"

      - name: Push to Codeberg Package Registry
        run: dotnet nuget push output/Mscc.GenerativeAI.*.nupkg --skip-duplicate -s codeberg -k ${{ secrets._NUGET_API_KEY }}

  build_and_push_dependents:
    name: Build and Push Dependent Packages to Codeberg
    needs: build_and_push_main
    strategy:
      matrix:
        os: [codeberg-small]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['10.x']
    runs-on: ${{ matrix.os }}

    steps:
      #    - name: Wait for Codeberg package propagation
      #      run: sleep 300

      - name: 📥 Check-out latest sources
        uses: actions/checkout@v6

      - name: 🔧 Set up .NET
        uses: https://github.com/actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
#          source-url: https://nuget.pkg.github.com/mscraftsman/index.json
        env:
#          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        
        # NetFX testing on non-Windows requires mono
      - name: 🔧 Setup Mono
        if: runner.os == 'Linux'
        run: sudo apt-get install -y mono-devel

#      - name: 🔧 Setup access to Codeberg Package Registry
#        run: dotnet nuget add source --username ${{ vars.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/mscraftsman/index.json"

      - name: Set NuGet source
        run: mv ./nuget.codeberg ./nuget.config

      - name: Restore Dependencies
        run: dotnet restore ./GenerativeAI.sln

      - name: 🏗️ Build
        run: dotnet build ./GenerativeAI.sln -c Release

      - name: 📦 Pack for ASP.NET Core
        run: dotnet pack -c Release ./src/Mscc.GenerativeAI.Web/Mscc.GenerativeAI.Web.csproj -o output/ --no-build

      - name: 📦 Pack for .NET using Google Cloud Client Library
        run: dotnet pack -c Release ./src/Mscc.GenerativeAI.Google/Mscc.GenerativeAI.Google.csproj -o output/ --no-build

      - name: 📦 Pack for Microsoft.Extension.AI and Microsoft Semantic Kernel
        run: dotnet pack -c Release ./src/Mscc.GenerativeAI.Microsoft/Mscc.GenerativeAI.Microsoft.csproj -o output/ --no-build

      - name: Push to Codeberg Package Registry
        run: |
          dotnet nuget push output/Mscc.GenerativeAI.Web.*.nupkg --skip-duplicate -s codeberg -k ${{ secrets._NUGET_API_KEY }}
          dotnet nuget push output/Mscc.GenerativeAI.Google.*.nupkg --skip-duplicate -s codeberg -k ${{ secrets._NUGET_API_KEY }}
          dotnet nuget push output/Mscc.GenerativeAI.Microsoft.*.nupkg --skip-duplicate -s codeberg -k ${{ secrets._NUGET_API_KEY }}