/*
 * Copyleft 2024-2025 Jochen Kirstätter and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using System.Text.Json.Serialization;

// *** AUTO-GENERATED FILE - DO NOT EDIT MANUALLY *** //

namespace Mscc.GenerativeAI.Types
{
	/// <summary>
	/// Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the <c>CodeExecution</c> tool, in which the code will be automatically executed, and a corresponding <c>CodeExecutionResult</c> will also be generated.
	/// </summary>
	public partial class ExecutableCode
	{
		/// <summary>
		/// Required. The code to be executed.
		/// </summary>
		public string? Code { get; set; }
		/// <summary>
		/// Required. Programming language of the <c>code</c>.
		/// </summary>
		public LanguageType? Language { get; set; }

		[JsonConverter(typeof(JsonStringEnumConverter<LanguageType>))]
		public enum LanguageType
		{
			/// <summary>
			/// Unspecified language. This value should not be used.
			/// </summary>
			LanguageUnspecified,
			/// <summary>
			/// Python &gt;= 3.10, with numpy and simpy available. Python is the default language.
			/// </summary>
			Python,
		}
    }
}