/*
 * Copyleft 2024-2025 Jochen Kirstätter and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// *** AUTO-GENERATED FILE - DO NOT EDIT MANUALLY *** //

namespace Mscc.GenerativeAI.Types
{
	/// <summary>
	/// A datatype containing media that is part of a multi-part <c>Content</c> message. A <c>Part</c> consists of data which has an associated datatype. A <c>Part</c> can only contain one of the accepted types in <c>Part.data</c>. A <c>Part</c> must have a fixed IANA MIME type identifying the type and subtype of the media if the <c>inline_data</c> field is filled with raw bytes.
	/// </summary>
	public partial class Part
	{
		/// <summary>
		/// Result of executing the <c>ExecutableCode</c>.
		/// </summary>
		public CodeExecutionResult? CodeExecutionResult { get; set; }
		/// <summary>
		/// Code generated by the model that is meant to be executed.
		/// </summary>
		public ExecutableCode? ExecutableCode { get; set; }
		/// <summary>
		/// URI based data.
		/// </summary>
		public FileData? FileData { get; set; }
		/// <summary>
		/// A predicted <c>FunctionCall</c> returned from the model that contains a string representing the <c>FunctionDeclaration.name</c> with the arguments and their values.
		/// </summary>
		public FunctionCall? FunctionCall { get; set; }
		/// <summary>
		/// The result output of a <c>FunctionCall</c> that contains a string representing the <c>FunctionDeclaration.name</c> and a structured JSON object containing any output from the function is used as context to the model.
		/// </summary>
		public FunctionResponse? FunctionResponse { get; set; }
		/// <summary>
		/// Custom metadata associated with the Part. Agents using genai.Part as content representation may need to keep track of the additional information. For example it can be name of a file/source from which the Part originates or a way to multiplex multiple Part streams.
		/// </summary>
		public object? PartMetadata { get; set; }
		/// <summary>
		/// Optional. Indicates if the part is thought from the model.
		/// </summary>
		public bool? Thought { get; set; }
		/// <summary>
		/// Optional. An opaque signature for the thought so it can be reused in subsequent requests.
		/// </summary>
		public byte[]? ThoughtSignature { get; set; }
		/// <summary>
		/// Optional. Video metadata. The metadata should only be specified while the video data is presented in inline_data or file_data.
		/// </summary>
		public VideoMetadata? VideoMetadata { get; set; }
    }
}