using System.Text.Json.Serialization;

namespace Mscc.GenerativeAI.Types
{
	[JsonConverter(typeof(JsonStringEnumConverter<Source>))]
    public enum Source
    {
        /// <summary>
        /// Used if source is not specified.
        /// </summary>
        SourceUnspecified,
        /// <summary>
        /// Indicates the file is uploaded by the user.
        /// </summary>
        Uploaded,
        /// <summary>
        /// Indicates the file is generated by Google.
        /// </summary>
        Generated,
        /// <summary>
        /// Indicates the file is a registered, i.e. a Google Cloud Storage file.
        /// </summary>
        Registered,
    }
}