#if NET472_OR_GREATER || NETSTANDARD2_0
using System.Text.Json.Serialization;
#endif

namespace Mscc.GenerativeAI
{
    /// <summary>
    /// Source of the File.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter<FileResourceSource>))]
    public enum FileResourceSource
    {
        /// <summary>
        /// Used if source is not specified.
        /// </summary>
        SourceUnspecified,
        /// <summary>
        /// Indicates the file is uploaded by the user.
        /// </summary>
        Uploaded,
        /// <summary>
        /// Indicates the file is generated by Google.
        /// </summary>
        Generated,
        /// <summary>
        /// Indicates the file is a registered, i.e. a Google Cloud Storage file.
        /// </summary>
        Registered
    }
}