namespace Mscc.GenerativeAI
{
    /// <summary>
    /// An image generated by the model.
    /// </summary>
    public class Image
    {
        /// <summary>
        /// A base64 encoded string of one (generated) image. (20 MB)
        /// </summary>
        public string? BytesBase64Encoded { get; set; }
        /// <summary>
        /// The IANA standard MIME type of the image.
        /// </summary>
        public string? MimeType { get; set; }
        /// <summary>
        /// Exists if storageUri is provided. The Cloud Storage uri where the generated images are stored.
        /// </summary>
        public string? GcsUri { get; set; }
        /// <summary>
        /// The image bytes data.
        /// <see cref="Image"/> can contain a value for this field or the `GcsUri` field but not both.
        /// </summary>
        public byte[]? ImageBytes { get; set; }
        /// <summary>
        /// The base64-encoded JSON of the generated image.
        /// </summary>
        public string? B64Json { get; set; }
    }
}