using System.Diagnostics;

namespace Mscc.GenerativeAI
{
    /// <summary>
    /// Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.
    /// </summary>
    [DebuggerDisplay("{Language}")]
    public class ExecutableCode : IPart
    {
        /// <summary>
        /// Required. Programming language of the `code`.
        /// </summary>
        public Language Language { get; set; }
        /// <summary>
        /// Required. The code to be executed.
        /// </summary>
        public string Code { get; set; }
    }
}