using System.Collections.Generic;

namespace Mscc.GenerativeAI
{
    /// <summary>
    /// The log probabilities of the tokens generated by the model. This is useful for understanding
    /// the model's confidence in its predictions and for debugging. For example, you can use log
    /// probabilities to identify when the model is making a less confident prediction or to explore
    /// alternative responses that the model considered. A low log probability can also indicate that
    /// the model is "hallucinating" or generating factually incorrect information.
    /// </summary>
    public class LogprobsResult
    {
        /// <summary>
        /// A list of the top candidate tokens at each decoding step. The length of this list is equal
        /// to the total number of decoding steps.
        /// </summary>
        public List<LogprobsResultTopCandidates>? TopCandidates { get; set; }
        /// <summary>
        /// A list of the chosen candidate tokens at each decoding step. The length of this list is
        /// equal to the total number of decoding steps. Note that the chosen candidate might not be in
        /// `top_candidates`.
        /// </summary>
        public List<LogprobsResultCandidate>? ChosenCanditates { get; set; }
        /// <summary>
        /// Sum of log probabilities for all tokens.
        /// </summary>
        /// <remarks>
        /// This data type is not supported in Vertex AI.
        /// </remarks>
        public float? LogProbabilitySum { get; set; }
    }
}