namespace Mscc.GenerativeAI
{
    /// <summary>
    /// Tool that executes code generated by the model, and
    /// automatically returns the result to the model.
    /// </summary>
    /// <remarks>
    /// See also `<see cref="ExecutableCode"/>` and `<see cref="CodeExecutionResult"/>`
    /// which are only generated when using this tool.
    /// </remarks>
    public class ToolCodeExecution : ITool
    {
        
    }
    
    public class CodeExecution : ToolCodeExecution
    {
        
    }
}