namespace Mscc.GenerativeAI
{
    /// <summary>
    /// Edit config object for model versions 006 and greater. All editConfig subfields are optional. If not specified, the default editing mode is inpainting.
    /// </summary>
    public class EditImageConfig : BaseConfig
    {
        /// <summary>
        /// The number of generated images.
        /// </summary>
        /// <remarks>Accepted integer values: 1-8 (v.002), 1-4 (v.005, v.006). Default value: 4.</remarks>
        public int? NumberOfImages { get; set; }

        /// <summary>
        /// Optional. The aspect ratio of the generated image.
        /// </summary>
        /// <remarks>Value: 1:1, 9:16*, 16:9*, 3:4*, or 4:3*</remarks>
        public string? AspectRatio { get; set; }

        /// <summary>
        /// Optional. Describes the editing mode for the request. One editing mode per request.
        /// </summary>
        public EditMode? EditMode { get; set; }

        /// <summary>
        /// Optional. Controls how much the model adheres to the text prompt. Large values increase output and prompt alignment, but may compromise image quality.
        /// </summary>
        /// <remarks>Values: 0-500 - Default: 60</remarks>
        public float? GuidanceScale { get; set; }

        /// <summary>
        /// Optional. Whether to enable rounded Responsible AI scores for a list of safety attributes in responses for unfiltered input and output.
        /// </summary>
        /// <remarks>Safety attribute categories: "Death, Harm and Tragedy", "Firearms and Weapons", "Hate", "Health", "Illicit Drugs", "Politics", "Porn", "Religion and Belief", "Toxic", "Violence", "Vulgarity", "War and Conflict".</remarks>
        public bool? IncludeSafetyAttributes { get; set; }

        /// <summary>
        /// Optional. The text prompt for guiding the response.
        /// </summary>
        /// <remarks>en (default), de, fr, it, es</remarks>
        public ImagePromptLanguage? Language { get; set; }

        /// <summary>
        /// Optional. Description of what to discourage in the generated images.
        /// </summary>
        //[Obsolete("Setting negativePrompt is no longer supported.")]
        public string? NegativePrompt { get; set; }

        /// <summary>
        /// Optional. The safety setting that controls the type of people or face generation allowed.
        /// </summary>
        /// <remarks>"personGeneration": "allow_all" is not available in Imagen 2 Editing and is only available to approved users‡ in Imagen 2 Generation.
        /// Values:
        /// allow_all: Allow generation of people of all ages.
        /// allow_adult (default): Allow generation of adults only.
        /// dont_allow: Disables the inclusion of people or faces in images.
        /// </remarks>
        public PersonGeneration? PersonGeneration { get; set; }

        /// <summary>
        /// Optional. The safety setting that controls safety filter thresholds.
        /// </summary>
        /// <remarks>Values:
        /// block_most: The highest threshold resulting in most requests blocked.
        /// block_some (default): The medium threshold that balances blocks for potentially harmful and benign content.
        /// block_few: Reduces the number of requests blocked due to safety filters. This setting might increase objectionable content generated by Imagen.
        /// </remarks>
        public SafetyFilterLevel? SafetyFilterLevel { get; set; }

        /// <summary>
        /// Cloud Storage URI used to store the generated images.
        /// </summary>
        public string? OutputGcsUri { get; set; }

        /// <summary>
        /// MIME type of the generated image.
        /// </summary>
        public string? OutputMimeType { get; set; }

        /// <summary>
        /// Compression quality of the generated image (for `image/jpeg` only).
        /// </summary>
        public int? OutputCompressionQuality { get; set; }

        /// <summary>
        /// Random seed for image generation. This is not available when add_watermark is set to true.
        /// </summary>
        public int? Seed { get; set; }
        
        /// <summary>
        /// Optional. 
        /// </summary>
        public MaskMode? MaskMode { get; set; }

        /// <summary>
        /// Optional. Determines the dilation percentage of the mask provided.
        /// </summary>
        /// <remarks>0.03 (3%) is the default value of shortest side. Minimum: 0, Maximum: 1</remarks>
        public float? MaskDilation { get; set; }

        /// <summary>
        /// Optional. Defines whether the detected product should stay fixed or be repositioned. If you set this field, you must also set "editMode": "product-image".
        /// </summary>
        /// <remarks>Values:
        /// reposition - Lets the model move the location of the detected product or object. (default value)
        /// fixed - The model maintains the original positioning of the detected product or object
        /// If the input image is not square, the model defaults to reposition.
        /// </remarks>
        public string? ProductPosition { get; set; }
    }
}