namespace Mscc.GenerativeAI.Types
{
	/// <summary>
	/// Tool that executes code generated by the model, and automatically returns the result to the model. See also <see cref="ExecutableCode"/> and <see cref="CodeExecutionResult"/> which are only generated when using this tool.
	/// </summary>
	public partial class CodeExecution
	{
    }
}
