namespace Mscc.GenerativeAI.Types
{
	/// <summary>
	/// Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the <see cref="CodeExecution"/> tool, in which the code will be automatically executed, and a corresponding <see cref="CodeExecutionResult"/> will also be generated.
	/// </summary>
	public partial class ExecutableCode
	{
		/// <summary>
		/// Required. The code to be executed.
		/// </summary>
		public string? Code { get; set; }
		/// <summary>
		/// Required. Programming language of the <see cref="code"/>.
		/// </summary>
		public Language? Language { get; set; }
    }
}
