using System.Text.Json.Serialization;

namespace Mscc.GenerativeAI.Types
{
	[JsonConverter(typeof(JsonStringEnumConverter<FinishReason>))]
    public enum FinishReason
    {
        /// <summary>
        /// Default value. This value is unused.
        /// </summary>
        FinishReasonUnspecified,
        /// <summary>
        /// Natural stop point of the model or provided stop sequence.
        /// </summary>
        Stop,
        /// <summary>
        /// The maximum number of tokens as specified in the request was reached.
        /// </summary>
        MaxTokens,
        /// <summary>
        /// The response candidate content was flagged for safety reasons.
        /// </summary>
        Safety,
        /// <summary>
        /// The response candidate content was flagged for recitation reasons.
        /// </summary>
        Recitation,
        /// <summary>
        /// The response candidate content was flagged for using an unsupported language.
        /// </summary>
        Language,
        /// <summary>
        /// Unknown reason.
        /// </summary>
        Other,
        /// <summary>
        /// Token generation stopped because the content contains forbidden terms.
        /// </summary>
        Blocklist,
        /// <summary>
        /// Token generation stopped for potentially containing prohibited content.
        /// </summary>
        ProhibitedContent,
        /// <summary>
        /// Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
        /// </summary>
        Spii,
        /// <summary>
        /// The function call generated by the model is invalid.
        /// </summary>
        MalformedFunctionCall,
        /// <summary>
        /// Token generation stopped because generated images contain safety violations.
        /// </summary>
        ImageSafety,
        /// <summary>
        /// Image generation stopped because generated images has other prohibited content.
        /// </summary>
        ImageProhibitedContent,
        /// <summary>
        /// Image generation stopped because of other miscellaneous issue.
        /// </summary>
        ImageOther,
        /// <summary>
        /// The model was expected to generate an image, but none was generated.
        /// </summary>
        NoImage,
        /// <summary>
        /// Image generation stopped due to recitation.
        /// </summary>
        ImageRecitation,
        /// <summary>
        /// Model generated a tool call but no tools were enabled in the request.
        /// </summary>
        UnexpectedToolCall,
        /// <summary>
        /// Model called too many tools consecutively, thus the system exited execution.
        /// </summary>
        TooManyToolCalls,
        /// <summary>
        /// Request has at least one thought signature missing.
        /// </summary>
        MissingThoughtSignature,
    }
}